### ISSUE TITLE
empty req.body when POST

### ISSUE THREAD

**Issue by lucischen** [indigofeather/laima#285]
I always get empty req.body when I '`POST`', 
and I find the answer at stackoverflow [req.body empty on posts.](http://stackoverflow.com/a/25904070/4104707)

Can you help me to add this to `mock/api.js` ?

**Comment by lucischen** [comment]
I'm using `Form-Data`,
but `body-parser` does not handle multipart bodies,
and I find another answer at [express](http://expressjs.com/en/4x/api.html#req.body)

**Comment by indigofeather** [comment]
OK, I will check
